version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-n8n.darwinyusef.com}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=${WEBHOOK_URL:-https://n8n.darwinyusef.com/}
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - TZ=America/Bogota
      - WHISPER_API_URL=http://whisper_api:8000
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - whisper_network

volumes:
  n8n_data:

networks:
  whisper_network:
    external: true
