global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'whisper_api'
    static_configs:
      - targets: ['api_gateway:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
